
services:
  dashboard:
    image: shrinidhi3012/aws-cost-optimizer-dashboard:latest
    ports:
      - "8501:8501"
    volumes:
      - ~/.aws:/root/.aws:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    container_name: aws-cost-optimizer-dashboard